import { PRInfo } from "./github";

export interface ReviewOutput {
  summary: string;
  risks: string[];
  suggestions: string[];
  confidence: "Low" | "Medium" | "High";
  filesAnalyzed: number;
}

export function analyzePR(pr: PRInfo): ReviewOutput {
  // Lightweight heuristic analysis (no external LLM call required for CLI tool)
  // This produces a structured review from the PR metadata and diff stats
  
  const riskPatterns: [RegExp, string][] = [
    [/password|secret|token|api_key|apikey|auth/i, "Hardcoded credentials or API keys detected"],
    [/\.env|\.local\.ini|config.*password/i, "Potential config file with sensitive data"],
    [/DROP TABLE|DELETE FROM.*WHERE|truncate/i, "Potentially destructive database operation"],
    [/eval\(|new Function\(|exec\(/i, "Dynamic code execution (security risk)"],
    [/console\.log|print\(|debugger/i, "Debug code left in production"],
    [/TODO|FIXME|HACK|XXX/i, "Unresolved code comments"],
    [/\.then\(\s*\(\s*\)\s*=>/i, "Missing .catch() on promise chain"],
    [/require\s*\(\s*['"]fs['"]\)/i, "File system access - ensure proper sandboxing"],
  ];

  const risks: string[] = [];
  for (const [pattern, message] of riskPatterns) {
    if (pattern.test(pr.diff)) {
      risks.push(message);
    }
  }

  // Estimate complexity
  const totalChanges = pr.additions + pr.deletions;
  const complexity = totalChanges > 500 ? "large" : totalChanges > 100 ? "medium" : "small";

  // Confidence based on diff size
  let confidence: "Low" | "Medium" | "High" = "Medium";
  if (pr.diff.length < 2000) confidence = "High";
  else if (pr.diff.length > 50000) confidence = "Low";

  const suggestions: string[] = [];
  if (pr.body.length < 20) suggestions.push("PR description is very brief - add more context");
  if (pr.additions > 300) suggestions.push("Large PR - consider splitting into smaller changes");
  if (risks.length > 2) suggestions.push("Review security implications before merging");
  if (!pr.diff.includes("test")) suggestions.push("No test changes detected - consider adding tests");
  if (pr.diff.includes("main") && !pr.diff.includes("master")) suggestions.push("Direct main branch modification - use feature branches");

  return {
    summary: `${pr.title} modifies ${pr.filesChanged.length} file(s) with ${pr.additions} additions and ${pr.deletions} deletions. This is a ${complexity} change.`,
    risks: risks.length > 0 ? risks : ["No obvious security risks detected in the diff."],
    suggestions: suggestions.length > 0 ? suggestions : ["Code looks reasonable - standard review practices apply."],
    confidence,
    filesAnalyzed: pr.filesChanged.length,
  };
}

export function formatMarkdown(pr: PRInfo, review: ReviewOutput): string {
  return `## 📋 PR Review: ${pr.title}

### Summary
${review.summary}

### 🔍 Risks
${review.risks.map((r) => `- ${r}`).join("\n")}

### 💡 Suggestions
${review.suggestions.map((s) => `- ${s}`).join("\n")}

### ✅ Confidence Score: **${review.confidence}**

---
*Analyzed ${review.filesAnalyzed} file(s) | ${pr.additions} additions / ${pr.deletions} deletions*
*Review generated by claude-review CLI*`;
}